export const authConstants = {
 LOGIN_REQUEST: "LOGIN_REQUEST",
 LOGIN_FAILURE: "LOGIN_FAILURE",
 LOGIN_SUCCESS: "LOGIN_SUCCESS",
 LOGOUT_REQUEST: "LOGOUT_REQUEST",
 LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
 LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
export const categoryConstansts = {
 GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
 GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
 GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
 ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
 ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
 ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
 UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
 UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
 UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
 DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
 DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
 DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",

 GET_CATEGORY_BY_ID_REQUEST: "GET_CATEGORY_BY_ID_REQUEST",
 GET_CATEGORY_BY_ID_SUCCESS: "GET_CATEGORY_BY_ID_SUCCESS",
 GET_CATEGORY_BY_ID_FAILURE: "GET_CATEGORY_BY_ID_FAILURE",
};
export const productConstants = {
 GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
 GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
 GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

 GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
 GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
 GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",

 GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
 GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
 GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

 GET_PRODUCT1_REQUEST: "GET_PRODUCT1_REQUEST",
 GET_PRODUCT1_SUCCESS: "GET_PRODUCT1_SUCCESS",
 GET_PRODUCT1_FAILURE: "GET_PRODUCT1_FAILURE",

 DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
 DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
 DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

 ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
 ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
 ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};
export const userConstants = {
 GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
 GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
 GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",

 GET_USER_BY_ID_REQUEST: "GET_USER_BY_ID_REQUEST",
 GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
 GET_USER_BY_ID_FAILURE: "GET_USER_BY_ID_FAILURE",

 DELETE_USER_BY_ID_REQUEST: "DELETE_USER_BY_ID_REQUEST",
 DELETE_USER_BY_ID_SUCCESS: "DELETE_USER_BY_ID_SUCCESS",
 DELETE_USER_BY_ID_FAILURE: "DELETE_USER_BY_ID_FAILURE",
}
export const orderConstants = {
 GET_ALL_ORDER_REQUEST: "GET_ALL_ORDER_REQUEST",
 GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
 GET_ALL_ORDER_FAILURE: "GET_ALL_ORDER_FAILURE",

 GET_ORDER_BY_ID_REQUEST: "GET_ORDER_BY_ID_REQUEST",
 GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
 GET_ORDER_BY_ID_FAILURE: "GET_ORDER_BY_ID_FAILURE",

 UPDATE_ORDER_BY_ID_REQUEST: "UPDATE_ORDER_BY_ID_REQUEST",
 UPDATE_ORDER_BY_ID_SUCCESS: "UPDATE_ORDER_BY_ID_SUCCESS",
 UPDATE_ORDER_BY_ID_FAILURE: "UPDATE_ORDER_BY_ID_FAILURE",
}